export const match_formation = {
    data : [
        {
            'type': '4-4-2',
            'name': 'Defender-1',
            'formation': {
                'player1_left': '34%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '40%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '51%',
                'player4_top': '4%',
                'player5_left': '51%',
                'player5_top': '40%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        },
        {
            'type': '4-3-3',
            'name': 'Defender-2',
            'formation': {
                'player1_left': '40%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '0%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '51%',
                'player4_top': '4%',
                'player5_left': '51%',
                'player5_top': '51%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        },
        {
            'type': '5-3-2',
            'name': 'Defender-3',
            'formation': {
                'player1_left': '34%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '40%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '51%',
                'player4_top': '27%',
                'player5_left': '51%',
                'player5_top': '4%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        },
        {
            'type': '4-5-1',
            'name': 'Defender-4',
            'formation': {
                'player1_left': '34%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '40%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '47%',
                'player4_top': '17%',
                'player5_left': '51%',
                'player5_top': '40%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        },
        {
            'type': '4-3-2-1',
            'name': 'Defender-5',
            'formation': {
                'player1_left': '34%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '20%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '51%',
                'player4_top': '4%',
                'player5_left': '51%',
                'player5_top': '40%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        },
        {
            'type': '4-4-1-1',
            'name': 'Defender-6',
            'formation': {
                'player1_left': '34%',
                'player1_top': '4%',
                'player2_left': '30%',
                'player2_top': '40%',
                'player3_left': '40%',
                'player3_top': '21%',
                'player4_left': '51%',
                'player4_top': '4%',
                'player5_left': '51%',
                'player5_top': '40%',
                'player6_left': '56%',
                'player6_top': '19%',
                'player7_left': '61%',
                'player7_top': '4%',
                'player8_left': '65%',
                'player8_top': '40%',
                'player9_left': '71%',
                'player9_top': '17%',
            }
        }
    ]
}

